os: osx
osx_image: xcode10.2
language: swift
script: xcodebuild clean build -workspace TravisTest/TravisTest.xcworkspace -scheme "TravisTest" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.2,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
